// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/food.proto

package foodpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FoodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FoodRequest) Reset() {
	*x = FoodRequest{}
	mi := &file_proto_food_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FoodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoodRequest) ProtoMessage() {}

func (x *FoodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_food_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FoodRequest.ProtoReflect.Descriptor instead.
func (*FoodRequest) Descriptor() ([]byte, []int) {
	return file_proto_food_proto_rawDescGZIP(), []int{0}
}

func (x *FoodRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FoodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FoodResponse) Reset() {
	*x = FoodResponse{}
	mi := &file_proto_food_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FoodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoodResponse) ProtoMessage() {}

func (x *FoodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_food_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FoodResponse.ProtoReflect.Descriptor instead.
func (*FoodResponse) Descriptor() ([]byte, []int) {
	return file_proto_food_proto_rawDescGZIP(), []int{1}
}

func (x *FoodResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

var File_proto_food_proto protoreflect.FileDescriptor

const file_proto_food_proto_rawDesc = "" +
	"\n" +
	"\x10proto/food.proto\x12\x06foodpb\"\x1d\n" +
	"\vFoodRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"&\n" +
	"\fFoodResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists2E\n" +
	"\vFoodService\x126\n" +
	"\tCheckFood\x12\x13.foodpb.FoodRequest\x1a\x14.foodpb.FoodResponseB\x0fZ\r/proto/foodpbb\x06proto3"

var (
	file_proto_food_proto_rawDescOnce sync.Once
	file_proto_food_proto_rawDescData []byte
)

func file_proto_food_proto_rawDescGZIP() []byte {
	file_proto_food_proto_rawDescOnce.Do(func() {
		file_proto_food_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_food_proto_rawDesc), len(file_proto_food_proto_rawDesc)))
	})
	return file_proto_food_proto_rawDescData
}

var file_proto_food_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_food_proto_goTypes = []any{
	(*FoodRequest)(nil),  // 0: foodpb.FoodRequest
	(*FoodResponse)(nil), // 1: foodpb.FoodResponse
}
var file_proto_food_proto_depIdxs = []int32{
	0, // 0: foodpb.FoodService.CheckFood:input_type -> foodpb.FoodRequest
	1, // 1: foodpb.FoodService.CheckFood:output_type -> foodpb.FoodResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_food_proto_init() }
func file_proto_food_proto_init() {
	if File_proto_food_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_food_proto_rawDesc), len(file_proto_food_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_food_proto_goTypes,
		DependencyIndexes: file_proto_food_proto_depIdxs,
		MessageInfos:      file_proto_food_proto_msgTypes,
	}.Build()
	File_proto_food_proto = out.File
	file_proto_food_proto_goTypes = nil
	file_proto_food_proto_depIdxs = nil
}
